//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acurus.Capella.PatientPortal.PatientPortalServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientPortalServiceReference.PatientPortalWebServiceSoap")]
    public interface PatientPortalWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldResponse HelloWorld(Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetPatientDetailsUsingPatientInformattionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPatientDetailsUsingPatientInformattion", ReplyAction="*")]
        Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionResponse GetPatientDetailsUsingPatientInformattion(Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientDetailsUsingPatientInformattionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatientDetailsUsingPatientInformattion", Namespace="http://tempuri.org/", Order=0)]
        public Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionRequestBody Body;
        
        public GetPatientDetailsUsingPatientInformattionRequest() {
        }
        
        public GetPatientDetailsUsingPatientInformattionRequest(Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPatientDetailsUsingPatientInformattionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong ulHumanID;
        
        public GetPatientDetailsUsingPatientInformattionRequestBody() {
        }
        
        public GetPatientDetailsUsingPatientInformattionRequestBody(ulong ulHumanID) {
            this.ulHumanID = ulHumanID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPatientDetailsUsingPatientInformattionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPatientDetailsUsingPatientInformattionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionResponseBody Body;
        
        public GetPatientDetailsUsingPatientInformattionResponse() {
        }
        
        public GetPatientDetailsUsingPatientInformattionResponse(Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPatientDetailsUsingPatientInformattionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPatientDetailsUsingPatientInformattionResult;
        
        public GetPatientDetailsUsingPatientInformattionResponseBody() {
        }
        
        public GetPatientDetailsUsingPatientInformattionResponseBody(string GetPatientDetailsUsingPatientInformattionResult) {
            this.GetPatientDetailsUsingPatientInformattionResult = GetPatientDetailsUsingPatientInformattionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientPortalWebServiceSoapChannel : Acurus.Capella.PatientPortal.PatientPortalServiceReference.PatientPortalWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientPortalWebServiceSoapClient : System.ServiceModel.ClientBase<Acurus.Capella.PatientPortal.PatientPortalServiceReference.PatientPortalWebServiceSoap>, Acurus.Capella.PatientPortal.PatientPortalServiceReference.PatientPortalWebServiceSoap {
        
        public PatientPortalWebServiceSoapClient() {
        }
        
        public PatientPortalWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientPortalWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientPortalWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientPortalWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldResponse Acurus.Capella.PatientPortal.PatientPortalServiceReference.PatientPortalWebServiceSoap.HelloWorld(Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldRequest inValue = new Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldRequest();
            inValue.Body = new Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldRequestBody();
            Acurus.Capella.PatientPortal.PatientPortalServiceReference.HelloWorldResponse retVal = ((Acurus.Capella.PatientPortal.PatientPortalServiceReference.PatientPortalWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionResponse Acurus.Capella.PatientPortal.PatientPortalServiceReference.PatientPortalWebServiceSoap.GetPatientDetailsUsingPatientInformattion(Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionRequest request) {
            return base.Channel.GetPatientDetailsUsingPatientInformattion(request);
        }
        
        public string GetPatientDetailsUsingPatientInformattion(ulong ulHumanID) {
            Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionRequest inValue = new Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionRequest();
            inValue.Body = new Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionRequestBody();
            inValue.Body.ulHumanID = ulHumanID;
            Acurus.Capella.PatientPortal.PatientPortalServiceReference.GetPatientDetailsUsingPatientInformattionResponse retVal = ((Acurus.Capella.PatientPortal.PatientPortalServiceReference.PatientPortalWebServiceSoap)(this)).GetPatientDetailsUsingPatientInformattion(inValue);
            return retVal.Body.GetPatientDetailsUsingPatientInformattionResult;
        }
    }
}
