//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace Acurus.Capella.DataAccess.com.labcorp.www4 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ABNServiceProxySoapBinding", Namespace="http://services.abn.labcorp.com")]
    public partial class ABNServiceProxyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback checkABNOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ABNServiceProxyService() {
            this.Url = global::Acurus.Capella.DataAccess.Properties.Settings.Default.Acurus_Capella_DataAccess_com_labcorp_www4_ABNServiceProxyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event checkABNCompletedEventHandler checkABNCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("checkABN", RequestNamespace="http://services.abn.labcorp.com", ResponseNamespace="http://services.abn.labcorp.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("checkABNReturn", IsNullable=true)]
        public AbnResponseType checkABN([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AbnRequestType abnRequest, bool includeABNContent, bool includeDetails, int nbrOfPrintCopies) {
            object[] results = this.Invoke("checkABN", new object[] {
                        abnRequest,
                        includeABNContent,
                        includeDetails,
                        nbrOfPrintCopies});
            return ((AbnResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void checkABNAsync(AbnRequestType abnRequest, bool includeABNContent, bool includeDetails, int nbrOfPrintCopies) {
            this.checkABNAsync(abnRequest, includeABNContent, includeDetails, nbrOfPrintCopies, null);
        }
        
        /// <remarks/>
        public void checkABNAsync(AbnRequestType abnRequest, bool includeABNContent, bool includeDetails, int nbrOfPrintCopies, object userState) {
            if ((this.checkABNOperationCompleted == null)) {
                this.checkABNOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckABNOperationCompleted);
            }
            this.InvokeAsync("checkABN", new object[] {
                        abnRequest,
                        includeABNContent,
                        includeDetails,
                        nbrOfPrintCopies}, this.checkABNOperationCompleted, userState);
        }
        
        private void OncheckABNOperationCompleted(object arg) {
            if ((this.checkABNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkABNCompleted(this, new checkABNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://databeans.abn.labcorp.com")]
    public partial class AbnRequestType {
        
        private string accountNumberField;
        
        private string[] diagCodesField;
        
        private string[] testCodesField;
        
        private string patientNameField;
        
        private string identificationNumberField;
        
        private string sourceNameField;
        
        private string sourceVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("diagCodes", IsNullable=true)]
        public string[] diagCodes {
            get {
                return this.diagCodesField;
            }
            set {
                this.diagCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("testCodes", IsNullable=true)]
        public string[] testCodes {
            get {
                return this.testCodesField;
            }
            set {
                this.testCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string patientName {
            get {
                return this.patientNameField;
            }
            set {
                this.patientNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string identificationNumber {
            get {
                return this.identificationNumberField;
            }
            set {
                this.identificationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sourceVersion {
            get {
                return this.sourceVersionField;
            }
            set {
                this.sourceVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://databeans.abn.labcorp.com")]
    public partial class AbnCpt {
        
        private string codeField;
        
        private string descField;
        
        private int priceField;
        
        private bool descNotFoundField;
        
        private bool priceNotFoundField;
        
        private int multiplierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public bool descNotFound {
            get {
                return this.descNotFoundField;
            }
            set {
                this.descNotFoundField = value;
            }
        }
        
        /// <remarks/>
        public bool priceNotFound {
            get {
                return this.priceNotFoundField;
            }
            set {
                this.priceNotFoundField = value;
            }
        }
        
        /// <remarks/>
        public int multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://databeans.abn.labcorp.com")]
    public partial class AbnTest {
        
        private AbnCpt[] freqCptsField;
        
        private AbnCpt[] medNecCptsField;
        
        private string testCodeField;
        
        private string ruoDescField;
        
        private bool ruoDescNotFoundField;
        
        private bool ruoIndicatorField;
        
        private int ruoPriceField;
        
        private bool ruoPriceNotFoundField;
        
        private string testDescField;
        
        private int testPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("freqCpts", IsNullable=true)]
        public AbnCpt[] freqCpts {
            get {
                return this.freqCptsField;
            }
            set {
                this.freqCptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("medNecCpts", IsNullable=true)]
        public AbnCpt[] medNecCpts {
            get {
                return this.medNecCptsField;
            }
            set {
                this.medNecCptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string testCode {
            get {
                return this.testCodeField;
            }
            set {
                this.testCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruoDesc {
            get {
                return this.ruoDescField;
            }
            set {
                this.ruoDescField = value;
            }
        }
        
        /// <remarks/>
        public bool ruoDescNotFound {
            get {
                return this.ruoDescNotFoundField;
            }
            set {
                this.ruoDescNotFoundField = value;
            }
        }
        
        /// <remarks/>
        public bool ruoIndicator {
            get {
                return this.ruoIndicatorField;
            }
            set {
                this.ruoIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public int ruoPrice {
            get {
                return this.ruoPriceField;
            }
            set {
                this.ruoPriceField = value;
            }
        }
        
        /// <remarks/>
        public bool ruoPriceNotFound {
            get {
                return this.ruoPriceNotFoundField;
            }
            set {
                this.ruoPriceNotFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string testDesc {
            get {
                return this.testDescField;
            }
            set {
                this.testDescField = value;
            }
        }
        
        /// <remarks/>
        public int testPrice {
            get {
                return this.testPriceField;
            }
            set {
                this.testPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://databeans.abn.labcorp.com")]
    public partial class Message {
        
        private string codeField;
        
        private string textField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://databeans.abn.labcorp.com")]
    public partial class AbnResponseType {
        
        private System.Nullable<bool> isABNRequiredField;
        
        private Message[] messagesField;
        
        private AbnTest[] abnTestsField;
        
        private string[] nonSpecificDiagnosisCodesField;
        
        private string[] invalidDiagnosisCodesField;
        
        private byte[] abnContentsField;
        
        private string contentTypeField;
        
        private int estCostField;
        
        private string outputTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isABNRequired {
            get {
                return this.isABNRequiredField;
            }
            set {
                this.isABNRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", IsNullable=true)]
        public Message[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("abnTests", IsNullable=true)]
        public AbnTest[] abnTests {
            get {
                return this.abnTestsField;
            }
            set {
                this.abnTestsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nonSpecificDiagnosisCodes", IsNullable=true)]
        public string[] nonSpecificDiagnosisCodes {
            get {
                return this.nonSpecificDiagnosisCodesField;
            }
            set {
                this.nonSpecificDiagnosisCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invalidDiagnosisCodes", IsNullable=true)]
        public string[] invalidDiagnosisCodes {
            get {
                return this.invalidDiagnosisCodesField;
            }
            set {
                this.invalidDiagnosisCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] abnContents {
            get {
                return this.abnContentsField;
            }
            set {
                this.abnContentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public int estCost {
            get {
                return this.estCostField;
            }
            set {
                this.estCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string outputType {
            get {
                return this.outputTypeField;
            }
            set {
                this.outputTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void checkABNCompletedEventHandler(object sender, checkABNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkABNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkABNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AbnResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AbnResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591