//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5448.
// 
#pragma warning disable 1591

namespace Acurus.Capella.DataAccess.QuestResultService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ResultsServicePort", Namespace="http://medplus.com/resultsHub/observations")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ProviderAccount))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(HL7Message))]
    public partial class ResultsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMoreResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback acknowledgeResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHL7ResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMoreHL7ResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback acknowledgeHL7ResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProviderAccountsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ResultsService() {
            this.Url = global::Acurus.Capella.DataAccess.Properties.Settings.Default.Acurus_Capella_DataAccess_QuestResultService_ResultsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getResultsCompletedEventHandler getResultsCompleted;
        
        /// <remarks/>
        public event getMoreResultsCompletedEventHandler getMoreResultsCompleted;
        
        /// <remarks/>
        public event acknowledgeResultsCompletedEventHandler acknowledgeResultsCompleted;
        
        /// <remarks/>
        public event getHL7ResultsCompletedEventHandler getHL7ResultsCompleted;
        
        /// <remarks/>
        public event getMoreHL7ResultsCompletedEventHandler getMoreHL7ResultsCompleted;
        
        /// <remarks/>
        public event acknowledgeHL7ResultsCompletedEventHandler acknowledgeHL7ResultsCompleted;
        
        /// <remarks/>
        public event getProviderAccountsCompletedEventHandler getProviderAccountsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://medplus.com/resultsHub/observations", ResponseNamespace="http://medplus.com/resultsHub/observations")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public ResultsResponse getResults(ResultsRequest resultsRequest) {
            object[] results = this.Invoke("getResults", new object[] {
                        resultsRequest});
            return ((ResultsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getResultsAsync(ResultsRequest resultsRequest) {
            this.getResultsAsync(resultsRequest, null);
        }
        
        /// <remarks/>
        public void getResultsAsync(ResultsRequest resultsRequest, object userState) {
            if ((this.getResultsOperationCompleted == null)) {
                this.getResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetResultsOperationCompleted);
            }
            this.InvokeAsync("getResults", new object[] {
                        resultsRequest}, this.getResultsOperationCompleted, userState);
        }
        
        private void OngetResultsOperationCompleted(object arg) {
            if ((this.getResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getResultsCompleted(this, new getResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://medplus.com/resultsHub/observations", ResponseNamespace="http://medplus.com/resultsHub/observations")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public ResultsResponse getMoreResults(string requestId) {
            object[] results = this.Invoke("getMoreResults", new object[] {
                        requestId});
            return ((ResultsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getMoreResultsAsync(string requestId) {
            this.getMoreResultsAsync(requestId, null);
        }
        
        /// <remarks/>
        public void getMoreResultsAsync(string requestId, object userState) {
            if ((this.getMoreResultsOperationCompleted == null)) {
                this.getMoreResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMoreResultsOperationCompleted);
            }
            this.InvokeAsync("getMoreResults", new object[] {
                        requestId}, this.getMoreResultsOperationCompleted, userState);
        }
        
        private void OngetMoreResultsOperationCompleted(object arg) {
            if ((this.getMoreResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMoreResultsCompleted(this, new getMoreResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://medplus.com/resultsHub/observations", ResponseNamespace="http://medplus.com/resultsHub/observations")]
        public void acknowledgeResults(string requestId, string[] acknowledgeMessages) {
            this.Invoke("acknowledgeResults", new object[] {
                        requestId,
                        acknowledgeMessages});
        }
        
        /// <remarks/>
        public void acknowledgeResultsAsync(string requestId, string[] acknowledgeMessages) {
            this.acknowledgeResultsAsync(requestId, acknowledgeMessages, null);
        }
        
        /// <remarks/>
        public void acknowledgeResultsAsync(string requestId, string[] acknowledgeMessages, object userState) {
            if ((this.acknowledgeResultsOperationCompleted == null)) {
                this.acknowledgeResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacknowledgeResultsOperationCompleted);
            }
            this.InvokeAsync("acknowledgeResults", new object[] {
                        requestId,
                        acknowledgeMessages}, this.acknowledgeResultsOperationCompleted, userState);
        }
        
        private void OnacknowledgeResultsOperationCompleted(object arg) {
            if ((this.acknowledgeResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acknowledgeResultsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://medplus.com/resultsHub/observations", ResponseNamespace="http://medplus.com/resultsHub/observations")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public HL7ResultsResponse getHL7Results(ResultsRequest resultsRequest) {
            object[] results = this.Invoke("getHL7Results", new object[] {
                        resultsRequest});
            return ((HL7ResultsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getHL7ResultsAsync(ResultsRequest resultsRequest) {
            this.getHL7ResultsAsync(resultsRequest, null);
        }
        
        /// <remarks/>
        public void getHL7ResultsAsync(ResultsRequest resultsRequest, object userState) {
            if ((this.getHL7ResultsOperationCompleted == null)) {
                this.getHL7ResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHL7ResultsOperationCompleted);
            }
            this.InvokeAsync("getHL7Results", new object[] {
                        resultsRequest}, this.getHL7ResultsOperationCompleted, userState);
        }
        
        private void OngetHL7ResultsOperationCompleted(object arg) {
            if ((this.getHL7ResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHL7ResultsCompleted(this, new getHL7ResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://medplus.com/resultsHub/observations", ResponseNamespace="http://medplus.com/resultsHub/observations")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public HL7ResultsResponse getMoreHL7Results(string requestId) {
            object[] results = this.Invoke("getMoreHL7Results", new object[] {
                        requestId});
            return ((HL7ResultsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getMoreHL7ResultsAsync(string requestId) {
            this.getMoreHL7ResultsAsync(requestId, null);
        }
        
        /// <remarks/>
        public void getMoreHL7ResultsAsync(string requestId, object userState) {
            if ((this.getMoreHL7ResultsOperationCompleted == null)) {
                this.getMoreHL7ResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMoreHL7ResultsOperationCompleted);
            }
            this.InvokeAsync("getMoreHL7Results", new object[] {
                        requestId}, this.getMoreHL7ResultsOperationCompleted, userState);
        }
        
        private void OngetMoreHL7ResultsOperationCompleted(object arg) {
            if ((this.getMoreHL7ResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMoreHL7ResultsCompleted(this, new getMoreHL7ResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://medplus.com/resultsHub/observations", ResponseNamespace="http://medplus.com/resultsHub/observations")]
        public void acknowledgeHL7Results(string requestId, HL7Message[] acknowledgeMessages) {
            this.Invoke("acknowledgeHL7Results", new object[] {
                        requestId,
                        acknowledgeMessages});
        }
        
        /// <remarks/>
        public void acknowledgeHL7ResultsAsync(string requestId, HL7Message[] acknowledgeMessages) {
            this.acknowledgeHL7ResultsAsync(requestId, acknowledgeMessages, null);
        }
        
        /// <remarks/>
        public void acknowledgeHL7ResultsAsync(string requestId, HL7Message[] acknowledgeMessages, object userState) {
            if ((this.acknowledgeHL7ResultsOperationCompleted == null)) {
                this.acknowledgeHL7ResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacknowledgeHL7ResultsOperationCompleted);
            }
            this.InvokeAsync("acknowledgeHL7Results", new object[] {
                        requestId,
                        acknowledgeMessages}, this.acknowledgeHL7ResultsOperationCompleted, userState);
        }
        
        private void OnacknowledgeHL7ResultsOperationCompleted(object arg) {
            if ((this.acknowledgeHL7ResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acknowledgeHL7ResultsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://medplus.com/resultsHub/observations", ResponseNamespace="http://medplus.com/resultsHub/observations")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public ProviderAccount[] getProviderAccounts() {
            object[] results = this.Invoke("getProviderAccounts", new object[0]);
            return ((ProviderAccount[])(results[0]));
        }
        
        /// <remarks/>
        public void getProviderAccountsAsync() {
            this.getProviderAccountsAsync(null);
        }
        
        /// <remarks/>
        public void getProviderAccountsAsync(object userState) {
            if ((this.getProviderAccountsOperationCompleted == null)) {
                this.getProviderAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProviderAccountsOperationCompleted);
            }
            this.InvokeAsync("getProviderAccounts", new object[0], this.getProviderAccountsOperationCompleted, userState);
        }
        
        private void OngetProviderAccountsOperationCompleted(object arg) {
            if ((this.getProviderAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProviderAccountsCompleted(this, new getProviderAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="java:com.medplus.serviceHub.results.webservice")]
    public partial class ResultsRequest {
        
        private string endDateField;
        
        private System.Nullable<int> maxMessagesField;
        
        private string[] providerAccountIdsField;
        
        private bool retrieveFinalsOnlyField;
        
        private bool retrieveObsoleteResultsField;
        
        private string startDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> maxMessages {
            get {
                return this.maxMessagesField;
            }
            set {
                this.maxMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] providerAccountIds {
            get {
                return this.providerAccountIdsField;
            }
            set {
                this.providerAccountIdsField = value;
            }
        }
        
        /// <remarks/>
        public bool retrieveFinalsOnly {
            get {
                return this.retrieveFinalsOnlyField;
            }
            set {
                this.retrieveFinalsOnlyField = value;
            }
        }
        
        /// <remarks/>
        public bool retrieveObsoleteResults {
            get {
                return this.retrieveObsoleteResultsField;
            }
            set {
                this.retrieveObsoleteResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="java:com.medplus.serviceHub.results.webservice")]
    public partial class Provider {
        
        private string descriptionField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="java:com.medplus.serviceHub.results.webservice")]
    public partial class ProviderAccount {
        
        private string accountIdField;
        
        private string accountNameField;
        
        private string descriptionField;
        
        private string descriptiveNameField;
        
        private string internalIdField;
        
        private Provider providerField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descriptiveName {
            get {
                return this.descriptiveNameField;
            }
            set {
                this.descriptiveNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string internalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Provider provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="java:com.medplus.serviceHub.results.webservice")]
    public partial class HL7Message {
        
        private string controlIdField;
        
        private byte[] messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string controlId {
            get {
                return this.controlIdField;
            }
            set {
                this.controlIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="java:com.medplus.serviceHub.results.webservice")]
    public partial class HL7ResultsResponse {
        
        private HL7Message[] hL7MessagesField;
        
        private System.Nullable<bool> isMoreField;
        
        private string requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public HL7Message[] HL7Messages {
            get {
                return this.hL7MessagesField;
            }
            set {
                this.hL7MessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isMore {
            get {
                return this.isMoreField;
            }
            set {
                this.isMoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="java:com.medplus.serviceHub.results.webservice")]
    public partial class ResultsResponse {
        
        private string[] hL7MessagesField;
        
        private System.Nullable<bool> isMoreField;
        
        private string requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] HL7Messages {
            get {
                return this.hL7MessagesField;
            }
            set {
                this.hL7MessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isMore {
            get {
                return this.isMoreField;
            }
            set {
                this.isMoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getResultsCompletedEventHandler(object sender, getResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getMoreResultsCompletedEventHandler(object sender, getMoreResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMoreResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMoreResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void acknowledgeResultsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getHL7ResultsCompletedEventHandler(object sender, getHL7ResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHL7ResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHL7ResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HL7ResultsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HL7ResultsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getMoreHL7ResultsCompletedEventHandler(object sender, getMoreHL7ResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMoreHL7ResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMoreHL7ResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HL7ResultsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HL7ResultsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void acknowledgeHL7ResultsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getProviderAccountsCompletedEventHandler(object sender, getProviderAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProviderAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProviderAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProviderAccount[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProviderAccount[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591