name: Capella CI/CD

on:
  workflow_dispatch:
    inputs:
      SERVER:
        description: "Target Server IP"
        required: true
        default: "10.0.0.4"

jobs:

  # ================= BUILD ================= #
  build:
    runs-on: self-hosted

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup NuGet
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Restore NuGet packages
      - name: Restore NuGet Packages
        run: |
          echo "NuGet restore start"
          nuget restore EHR-Capella5.0.sln
          echo "NuGet restore completed"

      # Ensure publish folder exists
      - name: Ensure publish folder exists
        run: mkdir "${{ github.workspace }}\publish"

      - name: Build & Publish
        run: |
          msbuild  EHR-Capella5.0.sln `
          /p:Configuration=Release `
          /p:DeployOnBuild=true `
          /p:PublishProfile=FolderProfile `
          /p:WebPublishMethod=FileSystem `
          /p:PublishUrl="${{ github.workspace }}\publish" `
          /p:DeleteExistingFiles=true `
          /p:Platform="Any CPU"

      # Upload published artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capella-build
          path: ${{ github.workspace }}\publish

      - name: Verify Publish Output
        run: |
         if (Test-Path "${{ github.workspace }}\publish") {
          echo "✅ Publish folder exists"
         dir "${{ github.workspace }}\publish"
         } else {
         echo "❌ Publish folder NOT created"
         exit 1
         }

  # ================= DEPLOY ================= #
  deploy:
    needs: build
    runs-on: windows-2022
    if: ${{ github.event.inputs.SERVER != '' }}

    steps:
      # Download artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: capella-build
          path: publish

      # Deploy to target server
      - name: Deploy to ${{ github.event.inputs.SERVER }}
        run: |
          echo "Backup Start"
          xcopy /y /s "E:\Acurus_Web\capella_cmg_project\capella_cmg_mt\*.*" "E:\Acurus_Web\Deployee\Backup-do not delete\Git\capella_cmg_mt"
          echo "Backup Completed"

          echo "Deploy Start"
          xcopy /y /s "publish\*.*" "E:\Acurus_Web\capella_cmg_project\capella_cmg_mt\"
          echo "Deploy Completed"
