name: Capella CI/CD

on:
  workflow_dispatch:
    inputs:
      SERVER:
        description: "Target Server IP"
        required: true
        default: "10.0.0.4"

jobs:

  # ================= BUILD ================= #
  build:
    runs-on: self-hosted

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup NuGet
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Restore NuGet packages
      - name: Restore NuGet Packages
        shell: cmd
        run: |
          echo "NuGet restore start"
          nuget restore EHR-Capella5.0.sln
          echo "NuGet restore completed"

      # Ensure publish folder exists
      - name: Ensure publish folder exists
        shell: cmd
        run: mkdir "${{ github.workspace }}\publish"

      - name: Build Solution
        shell: cmd
        run: |
         msbuild EHR-Capella5.0.sln ^
         /p:Configuration=Release ^
         /p:DeployOnBuild=true ^
         /p:WebPublishMethod=FileSystem ^
         /p:PublishUrl="%GITHUB_WORKSPACE%\publish" ^
         /p:DeleteExistingFiles=true ^
         /p:Platform="Any CPU"
         
      # Upload published artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capella-build
          path: ${{ github.workspace }}\publish

      - name: Verify Publish Output
        shell: powershell
        run: |
          if (Test-Path "C:\actions-runner\_work\EHR_8.0\EHR_8.0\publish") {
              Write-Host "Publish folder exists"
              Get-ChildItem "C:\actions-runner\_work\EHR_8.0\EHR_8.0\publish"
          } else {
              Write-Host "Publish folder NOT found"
              exit 1
          }

  # ================= DEPLOY ================= #
  deploy:
    needs: build
    runs-on: windows-2022
    if: ${{ github.event.inputs.SERVER != '' }}

    steps:
      # Download artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: capella-build
          path: publish

      # Deploy to target server
      - name: Deploy to ${{ github.event.inputs.SERVER }}
        run: |
          echo "Backup Start"
          xcopy /y /s "E:\Acurus_Web\capella_cmg_project\capella_cmg_mt\*.*" "E:\Acurus_Web\Deployee\Backup-do not delete\Git\capella_cmg_mt"
          echo "Backup Completed"

          echo "Deploy Start"
          xcopy /y /s "publish\*.*" "E:\Acurus_Web\capella_cmg_project\capella_cmg_mt\"
          echo "Deploy Completed"
